name: moncli
description: A sample command-line application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  args: ^2.0.0
  dcli: ^0.51.9

dev_dependencies: 
  very_good_analysis: ^2.0.0
  test: ^1.14.4
