name: moncli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
 args: ^2.0.0
 dcli: ^0.51.9

dev_dependencies:
  # pedantic: ^1.11.0
  # lint: ^1.5.3
  very_good_analysis: ^2.0.0
  test: ^1.14.4
