name: moncli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.0.0
  dcli: ^0.51.9
  http: ^0.13.1
  recase: ^4.0.0
  yaml: ^3.1.0



dev_dependencies:
  # pedantic: ^1.11.0
  build_runner: ^2.0.4
  lint: ^1.5.3
  mockito: ^5.0.9
  # very_good_analysis: ^2.0.0
  test: ^1.14.4